name = "ideavault-auth"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ideavault"
database_id = "0c29c45e-c89f-45b8-b422-b4ccc6bdf235"

[vars]
NOTES_WORKER_URL = "https://ideavault-notes.ideavault.workers.dev"
STRIPE_PRICE_ID = "price_1Q5H1eBkMaO1XBH5J0NxHnNs"

# wrangler secret put JWT_SECRET
# wrangler secret put STRIPE_SECRET
# wrangler secret put STRIPE_WEBHOOK_SECRET
